<?php

namespace AppBundle\Repository;

/**
 * CardTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
